### PR TITLE
Update okcalls64.h

### PR DESCRIPTION
**Pull request by 18323**

### CODE REVIEW

**Comment by 18323** [comment]
Sorry for the trouble! I am a beginner of the C language, and I practiced the questions on the codeup website before. The website reported the following error:
Runtime Error:[Error] A Not allowed system call: runid:1386138 CALLID:13
TO FIX THIS, ask admin TO add the CALLID into corresponding LANG_XXV[] located at okcalls32/64. H,
And recompile judge_client.
If you are admin and you don't know what to do,
Chinese explaination can be found on https://zhuanlan.zhihu.com/p/24498599
In fact, I can't understand the solution you provided or the solution I found on the Internet. I probably did some operations on hustoj.I  Could you please give me some help?
Thank you very much!

**Comment by zhblue** [comment]
sure，would you like to show me the code of your solution-id:1386138

**Comment by 18323** [comment]
id:1386138：Pascal's triangle,Here is my solution:
#include <stdio.h>
#include <stdlib.h>
#define N 10
 
int main(void)
{
    int n;
    int i,j;
    int a[N][N] = {0};
    scanf("%d",&n);
    for(i = 0; i < n; i++)
    {
        a[i][0] = 1;
        printf("%d",a[i][0]);
        for(j = 1; j <= i; j++)
        {
            a[i][j] = a[i-1][j-1] + a[i-1][j] ;
            printf("%2d",a[i][j]);
        }   
        printf("\n");
    }
    system ("pause");
    return 0; 
}

**Comment by zhblue** [comment]
system ("pause");  is not acceptable with OJ

**Comment by zhblue** [comment]
try remove system call and try again.

**Comment by 18323** [comment]
I have solved the problem with your help.Thank you very much!

**Pull request closed without merging**
