### PR TITLE
Move logger to logger.php and add switchs

### PR DESCRIPTION
**Pull request by mjiuming**
```php
/* log */
static  $OJ_LOG_ENABLED=false;
static  $OJ_LOG_FILE="/var/log/hustoj/hustoj.log";
static  $OJ_LOG_DATETIME_FORMAT="Y-m-d H:i:s";
static  $OJ_LOG_PID_ENABLED=false;
static  $OJ_LOG_USER_ENABLED=false;
static  $OJ_LOG_URL_ENABLED=false;
static  $OJ_LOG_URL_HOST_ENABLED=false;
static  $OJ_LOG_URL_PARAM_ENABLED=false;
static  $OJ_LOG_TRACE_ENABLED=false;
```

### CODE REVIEW

**Comment by zhblue** [comment]
what if people have multiple instances on same server ？

**Comment by mjiuming** [comment]
What means multiple instances on same server? Multiply HUSTOJ or Multiply Request?
If user has multiply HUSTOJ, then he should just change `$OJ_LOG_FILE="/var/log/hustoj/hustoj.log"; `, this place is just a default value.
If use has multiply request and trace each request, set `$OJ_LOG_TRACE_ENABLED=true;`, then logger will auto generate unique id to trace log in full request

**Comment by zhblue** [comment]
Multiply HUSTOJ , especially when they trying upgrade to latest web code.
so i suggest you change the default value to
```
$OJ_LOG_FILE="/var/log/hustoj/".$_SERVER['HTTP_HOST']."log";
```

**Comment by zhblue** [comment]
and add directory making of "/var/log/hustoj/"
in install/update-hustoj script

**Comment by mjiuming** [comment]
Maybe `$OJ_LOG_FILE="/var/log/hustoj/".$OJ_NAME."log";` is bette.

**Comment by zhblue** [comment]
better it is

**Comment by mjiuming** [comment]
This feature in WORK IN PROGRESS, and I would add directory making in install and update script

**Comment by mjiuming** [comment]
`$OJ_LOG_FILE="/var/log/hustoj/{$OJ_NAME}.log";` is finished

**Pull request merged**
