### PR TITLE
Avoid Compiler Bomb

### PR DESCRIPTION
**Pull request by ryanlee2014**
Avoid Compiler Bomb like:
int main() {
    struct x struct z<x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(y,x(y><y*,x(y*w>v<y*,w,x{}
    return 0; 
}

### CODE REVIEW

**Comment by zhblue** [comment]
tried your code on my system
Main.c: In function ‘main’:
Main.c:2:14: error: two or more data types in declaration specifiers
     struct x struct z<x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(y,x(y><y*,x(y*w>v<y*,w,x{}
              ^
Main.c:2:22: error: expected identifier or ‘(’ before ‘<’ token
     struct x struct z<x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(y,x(y><y*,x(y*w>v<y*,w,x{}

**Comment by ryanlee2014** [comment]
But in my environment it can be like this
CentOS gcc 4.8.5
3da9bfd9-f62e-47d8-8d39-39b6ca5e7aed
Ubuntu 17.04 gcc 7.2.0
qq20180529-215746
It's risky if judger doesn't limits the maximum number of error messages

**Comment by zhblue** [comment]
the judge_client should has limited the resource of compiler, if your OJ instance crash on compiling ,try update to the latest version.

**Comment by zhblue** [comment]
thank you for your pr ,i will consider to add these modifications

**Pull request merged**
