### PR TITLE
Update status.php

### PR DESCRIPTION
**Pull request by YYQHoro**
fix xss. for example  problem_id=%20onmouseover=lcksfj(6545)%20var=%20

### CODE REVIEW

**Comment by zhblue** [comment]
but there is "htmlentities" and "intval" above , i'm not sure these modification is needed

**Comment by YYQHoro** [comment]
for these <a>   like     [<a href=status.php?".$str2.">Top</a>]&nbsp;&nbsp;";

**Comment by YYQHoro** [comment]
%20 blank

**Comment by zhblue** [comment]
i mean problem_id has already been filter once 
https://github.com/zhblue/hustoj/blob/master/trunk/web/status.php#L86
and
https://github.com/zhblue/hustoj/blob/master/trunk/web/status.php#L92
L86 htmlentities is similiar to htmlspecialchar
L92 will not accept any char except digitals

**Comment by YYQHoro** [comment]
but the %20 blank is accepted. try the example,and see the console when mouse is on [Top]  [Previous Page]  [Next Page]

**Comment by zhblue** [comment]
try this patch 
https://github.com/zhblue/hustoj/commit/20d7701fdb5bbb6f922bb8ca1e3eeb9fe324eb61

**Comment by zhblue** [comment]
and this
https://github.com/zhblue/hustoj/commit/9f5ebd737771a396aa31d882b108a09f0500f49c

**Pull request merged**
